<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="apples-MacBook-Air.local" name="TestCases.DemoTest" tests="2" failures="1" timestamp="2023-01-05T08:29:03 IST" time="11.236" errors="0">
  <testcase name="verifyTitleTest1" time="11.236" classname="TestCases.DemoTest">
    <failure type="java.lang.AssertionError" message="Test case fail zali ka expected [Swag Labs] but found [1Swag Labs]">
      <![CDATA[java.lang.AssertionError: Test case fail zali ka expected [Swag Labs] but found [1Swag Labs]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at TestCases.DemoTest.verifyTitleTest1(DemoTest.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:51)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:41)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- verifyTitleTest1 -->
  <testcase name="verifyTitleTest" classname="TestCases.DemoTest">
    <skipped/>
  </testcase> <!-- verifyTitleTest -->
</testsuite> <!-- TestCases.DemoTest -->
